version: "3.7"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    hostname: sql
    networks:
      - mydev.local
    ports:
      - "1433:1433"
    volumes:
      - "mssqldata:/var/opt/mssql"
      - "./data:/data"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQLS3rv3r
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_PID=Express
    entrypoint:
      - /bin/bash
      - /data/entrypoint.sh
    command: [ "/opt/mssql/bin/sqlservr" ]
  coldfusion:
    image: public.ecr.aws/adobe/coldfusion:latest-2018
    container_name: coldfusion
    hostname: coldfusion
    networks:
      - mydev.local
    ports:
      - "80:8500"
    volumes:
      - "./app:/app"
      - "./data:/data"
    environment:
      acceptEULA: "YES"
      password: "C0ldFusi0n"
      enableSecureProfile: "false"
    healthcheck:
      test: curl -f http://localhost/
      interval: 1m
      timeout: 3s
    depends_on:
      - sql
volumes:
  mssqldata:
networks:
  mydev.local:
   name: mydev.local
